language: ruby
  
rvm:
      - 2.6.1

addons:
        postgresql: "10"
        apt:
                packages:
                - postgresql-10
                - postgresql-client-10
notifications:
        email: false

env:
        global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
        - CC_TEST_REPORTER_ID=4f2fd215528f279ecf795d2fefdcfd7d7c97aa4e07edc6210f2edccd1cd4bbf4
        - PGPORT=5433

before_install: 
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - sudo locale-gen --no-archive es_CO.UTF-8
        - sudo /etc/init.d/postgresql stop
        - sudo /etc/init.d/postgresql start 10
        - cd test/dummy
        - psql -c 'CREATE DATABASE mr519gen_pru;' -U postgres
        - gem install bundler
        - gem update --system
        - bundle update --bundler
        - bundle install
        - cp db/structure.sql db/structure.sql.copia
        - sed -e "s/provider = libc,//g" db/structure.sql.copia >db/structure.sql
        - cp config/database.travis.yml config/database.yml
        - rake db:setup
        - rake sip:indices
        - cd ../..

script: 
        - bundle exec rails test -b

after_script: 
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
